version:                   '2.2'
services:

# pgSQL server
  pgsql:
    restart:               always
    image:                 postgres
    container_name:        pgsql
    hostname:              pgsql
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: 'soviet16'
        POSTGRES_USER:     'towaristch'
        POSTGRES_DB:       'towaristch_site'
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - towaristch

# pgadmin for pgSQL
  pgadmin:
    container_name:        pgadmin
    hostname:              pgadmin
    image:                 dpage/pgadmin4
    restart:               always
    ports:
      - 8080:80
    environment:
        PGADMIN_DEFAULT_EMAIL: 'mif36rus@gmail.com'
        PGADMIN_DEFAULT_PASSWORD: 'soviet16'
    networks:
      - towaristch

volumes:
  pgdata:
    driver:                local

# towaristch local network for apps
networks:
  towaristch:
