version:            '2.2'
services:

# pgSQL server
  pgsql:
    restart:        always
    image:          postgres
    container_name: pgsql
    hostname:       pgsql
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=towaristch
      - DB_PASS=soviet16
      - DB_NAME=towaristch_site
#      - DB_TEMPLATE=
#      - DB_EXTENSION=
#      - REPLICATION_MODE=
#      - REPLICATION_USER=
#      - REPLICATION_PASS=
#      - REPLICATION_SSLMODE=
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - towaristch

# adminer for pgSQL
  adminer:
    container_name: pg-adminer
    hostname:       pg-adminer
    image:          adminer
    restart:        always
    ports:
      - 8080:8080
    networks:
      - towaristch

volumes:
  pgdata:
    driver:         local

# towaristch local network for apps
networks:
  towaristch:
